# Generated by Django 3.1.13 on 2022-01-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(blank=True)),
                ('ordering', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'FAQ-Question',
                'verbose_name_plural': 'FAQ-Questions',
                'ordering': ['ordering'],
            },
        ),
    ]
