# Generated by Django 5.2 on 2025-05-19 18:05

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
