"""
Django settings for mks project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

VERSION = "3.0.2"

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# Secret Key stored in local_settings
SECRET_KEY = 'jb#172ifl0xe55c9ed(=9i4erh*oj3nj)in%$9s3*1o9hr#$v^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'mks.apps.MksConfig',  # Must be first to setup allauth compatibility
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    #'debug_toolbar',
    'users.apps.UsersConfig',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # mks_apps
    'phone_field',
    'location.apps.LocationConfig',
    'students.apps.StudentsConfig',
    'teaching.apps.TeachingConfig',
    'home',
    'tinymce',  # Added TinyMCE
    'blog.apps.BlogConfig',
    'school.apps.SchoolConfig',
    'instruments.apps.InstrumentsConfig',
    'events.apps.EventsConfig',
    'gallery.apps.GalleryConfig',
    'maintenance.apps.MaintenanceConfig',  # Wartungsmodus
    'contact.apps.ContactConfig',
    'controlling.apps.ControllingConfig',
    'downloadsection.apps.DownloadsectionConfig',
    'todo',
    'tests.apps.TestsConfig',  # Test Suite mit Management Commands
    'projects.apps.ProjectsConfig',
    'faq.apps.FaqConfig',
    'invitation.apps.InvitationConfig',
    'dance', # Add the new dance app
    'midi_band', # Add the new midi-band app
    #sitemaps
    'django.contrib.sitemaps',
    #thumbnails
    'sorl.thumbnail',
    #user-agents
    'django_user_agents',
    #excel-export
    'xlwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'users.middleware.TwoFactorSetupRedirectMiddleware',  # TEMPORÄR DEAKTIVIERT
    'django.contrib.messages.middleware.MessageMiddleware',
    'maintenance.middleware.MaintenanceModeMiddleware',  # Wartungsmodus
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Smart compatibility middleware for allauth (works with all versions)
]

ROOT_URLCONF = 'mks.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'maintenance.context_processors.maintenance_context',  # Wartungsmodus
            ],
        },
    },
]

WSGI_APPLICATION = 'mks.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mks',
        'USER': 'postgres',
        'PASSWORD': 'Ax9kl3',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.CustomUser'

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",

    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
)

SITE_ID = 1

#LOGIN SUCESS TO URL
LOGIN_REDIRECT_URL = '/team/'

#LOGUT
LOGOUT_REDIRECT_URL = '/'

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)
# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'de'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    'plugins': '''
            powerpaste casechange searchreplace autolink directionality
            advcode visualblocks visualchars image link media mediaembed codesample table
            charmap pagebreak nonbreaking anchor advlist lists wordcount help formatpainter
            permanentpen checklist export linkchecker tinymcespellchecker
            tinydrive mentions tinycomments footnotes mergetags advtable export
            ''',
    'toolbar': '''
            undo redo print spellcheckdialog formatpainter | blocks fontfamily fontsize |
            bold italic underline forecolor backcolor | link image media | alignleft aligncenter
            alignright alignjustify | outdent indent | removeformat | code | table |
            lists numlist bullist checklist | charmap emoticons |
            fullscreen preview | save export searchreplace
            ''',
    'height': 500,
    'width': '100%',
    'menubar': True,
    'statusbar': True,
    'relative_urls': False,
    'remove_script_host': False,
    'convert_urls': True,
    'valid_elements': '*[*]',
    'valid_children': '+body[style]',
    'custom_elements': 'style,~style',
    'extended_valid_elements': '''
            style[type],
            script[type|src],
            iframe[src|style|width|height|scrolling|marginwidth|marginheight|frameborder],
            img[class|src|border|alt|title|hspace|vspace|width|height|align|name],
            a[class|name|href|target|title|rel],
            span[class|style],
            div[class|style],
            p[class|style]
            ''',
    'content_css': 'default',
    'browser_spellcheck': True,
    'contextmenu': 'link image table',
    'branding': False,  # Disable TinyMCE branding
    'promotion': False,  # Disable promotion messages
    'resize': 'both',  # Allow resizing
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    #'/var/www/static/',
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static_cdn')

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

FIXTURE_DIRS = [
    os.path.join(BASE_DIR, 'fixtures'),
]

# Commented out to prevent automatic loading during tests
# FIXTURES = [
#     'dance/fixtures/dance_data.json',
# ]

EMAIL_HOST = 'localhost'
EMAIL_PORT = 25
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_USER_RECEIVER = 'musikschule@st-poelten.gv.at'

DEFAULT_AUTO_FIELD='django.db.models.AutoField' 

THUMBNAIL_FORCE_OVERWRITE = True

# Default storage configuration
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

USER_AGENTS_CACHE = 'default'

APPEND_SLASH = True

if os.path.isfile(os.path.join(BASE_DIR, 'local_settings.py')):
    from local_settings import *

# Additional Blog Settings - Add these to the end of settings.py

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000  # For formsets with many fields

# Ensure logs directory exists
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
try:
    if not os.path.exists(LOGS_DIR):
        os.makedirs(LOGS_DIR, exist_ok=True)
    # Test if we can write to the logs directory
    test_file = os.path.join(LOGS_DIR, 'test.log')
    with open(test_file, 'w') as f:
        f.write('test')
    os.remove(test_file)
    LOGGING_ENABLED = True
except (OSError, PermissionError):
    # If we can't create/write to logs directory, disable file logging
    LOGGING_ENABLED = False

# Logging Configuration
if LOGGING_ENABLED:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
                'formatter': 'verbose',
            },
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
        },
        'loggers': {
            'blog': {
                'handlers': ['file', 'console'],
                'level': 'INFO',
                'propagate': True,
            },
            'django': {
                'handlers': ['file'],
                'level': 'ERROR',
                'propagate': True,
            },
        },
    }
else:
    # Fallback logging configuration without file handler
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
        },
        'loggers': {
            'blog': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': True,
            },
            'django': {
                'handlers': ['console'],
                'level': 'ERROR',
                'propagate': True,
            },
        },
    }

# Enhanced TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG.update({
    'automatic_uploads': True,
    'images_reuse_filename': True,
    'paste_data_images': True,
    'content_style': 'body { font-family: Arial, sans-serif; font-size: 14px; }',
    'setup': '''
        function (editor) {
            editor.on('change', function () {
                editor.save();
            });
        }
    ''',
})

# Session Configuration
SESSION_COOKIE_AGE = 3600 * 24 * 7  # 1 week
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Media Upload Security
ALLOWED_IMAGE_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp']
MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10MB
