# Generated by Django 4.0.4 on 2022-05-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_coordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='coordinator',
        ),
        migrations.AddField(
            model_name='customuser',
            name='coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
