# Generated by Django 5.2.1 on 2025-05-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_coordinator_customuser_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='Backup codes for 2FA'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, help_text='Two-Factor Authentication enabled'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='TOTP secret key', max_length=32, null=True),
        ),
    ]
