# Generated by Django 5.2.1 on 2025-05-23 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_backup_codes_customuser_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Rollenname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_view_students', models.BooleanField(default=False, verbose_name='Schüler anzeigen')),
                ('can_edit_students', models.BooleanField(default=False, verbose_name='Schüler bearbeiten')),
                ('can_delete_students', models.BooleanField(default=False, verbose_name='Schüler löschen')),
                ('can_view_teachers', models.BooleanField(default=False, verbose_name='Lehrkräfte anzeigen')),
                ('can_edit_teachers', models.BooleanField(default=False, verbose_name='Lehrkräfte bearbeiten')),
                ('can_delete_teachers', models.BooleanField(default=False, verbose_name='Lehrkräfte löschen')),
                ('can_view_events', models.BooleanField(default=False, verbose_name='Veranstaltungen anzeigen')),
                ('can_edit_events', models.BooleanField(default=False, verbose_name='Veranstaltungen bearbeiten')),
                ('can_delete_events', models.BooleanField(default=False, verbose_name='Veranstaltungen löschen')),
                ('can_view_gallery', models.BooleanField(default=False, verbose_name='Galerie anzeigen')),
                ('can_edit_gallery', models.BooleanField(default=False, verbose_name='Galerie bearbeiten')),
                ('can_delete_gallery', models.BooleanField(default=False, verbose_name='Galerie löschen')),
                ('can_view_controlling', models.BooleanField(default=False, verbose_name='Controlling anzeigen')),
                ('can_export_data', models.BooleanField(default=False, verbose_name='Daten exportieren')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Benutzer verwalten')),
                ('can_manage_roles', models.BooleanField(default=False, verbose_name='Rollen verwalten')),
            ],
            options={
                'verbose_name': 'Benutzerrolle',
                'verbose_name_plural': 'Benutzerrollen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.userrole', verbose_name='Benutzerrolle'),
        ),
    ]
