# Generated by Django 5.2.1 on 2025-05-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userrole_customuser_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='twofa_reset_code',
            field=models.CharField(blank=True, help_text='2FA reset code', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twofa_reset_expires',
            field=models.DateTimeField(blank=True, help_text='2FA reset code expiration', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
