# Generated by Django 2.2.5 on 2019-10-08 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of school')),
                ('image', models.ImageField(blank=True, default='event_default.jpg', upload_to='events/images/')),
                ('venue', models.CharField(blank=True, max_length=50, verbose_name='Venue')),
                ('date', models.DateField(blank=True, default=datetime.date.today, verbose_name='date for event')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('date',),
            },
        ),
    ]
