# Generated by Django 2.2.5 on 2019-10-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191008_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='Event Time '),
        ),
    ]
