# Generated by Django 2.2.5 on 2019-10-21 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import students.day_of_weeks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_title', models.CharField(max_length=4, verbose_name='Titel')),
            ],
            options={
                'verbose_name': 'academic title',
                'verbose_name_plural': 'academic titles',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=6, verbose_name='gender')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('image', models.ImageField(blank=True, default='student_imageDefault', upload_to='students/images/')),
                ('regular_lesson_time', models.TimeField(blank=True, db_index=True, help_text='if lessonform is monthly', null=True, verbose_name='regular lesson time ')),
                ('regular_lesson_day', students.day_of_weeks.DayOfTheWeekField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], help_text='if lessonform is monthly', max_length=1, null=True, verbose_name='regular lesson day')),
                ('lesson_count', models.IntegerField(default=0, verbose_name='lesson counter')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='start date')),
                ('phone', phone_field.models.PhoneField(blank=True, default='+43 ', help_text='Telefonnummer', max_length=31, verbose_name='telephone number')),
                ('email', models.EmailField(blank=True, max_length=70, verbose_name='e-mail')),
                ('iban', models.CharField(blank=True, max_length=20, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=20, verbose_name='BIC')),
                ('adress_line', models.CharField(blank=True, max_length=80, verbose_name='street')),
                ('house_number', models.CharField(blank=True, max_length=80, verbose_name='house number')),
                ('postal_code', models.CharField(blank=True, max_length=30, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='city')),
                ('academic_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.AcademicTitle')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Country')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Gender')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ('last_name',),
            },
        ),
    ]
