# Generated by Django 2.2.5 on 2019-09-27 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('location', '0001_initial'),
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lesson_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teaching.LessonForm'),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teaching.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teaching.Teacher'),
        ),
    ]
