# Generated by Django 2.2.5 on 2019-11-29 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191021_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Gender'),
        ),
    ]
