# Generated by Django 2.2.5 on 2019-12-01 15:28

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20191130_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Nachname'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('phone', phone_field.models.PhoneField(blank=True, default='+43 ', help_text='Telefonnummer', max_length=31, verbose_name='telephone number')),
                ('email', models.EmailField(blank=True, max_length=70, verbose_name='e-mail')),
                ('adress_line', models.CharField(blank=True, max_length=80, verbose_name='street')),
                ('house_number', models.CharField(blank=True, max_length=80, verbose_name='house number')),
                ('postal_code', models.CharField(blank=True, max_length=30, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='city')),
                ('academic_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.AcademicTitle')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Gender')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ('last_name',),
            },
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Parent'),
        ),
    ]
