# Generated by Django 3.2.12 on 2022-03-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-start_date', 'last_name'), 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
