# Generated by Django 3.2.13 on 2022-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
