# Generated by Django 3.0.3 on 2020-02-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teaching', '0008_auto_20191213_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('lead_paragraph', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='project_imageDefault', upload_to='project/images/')),
                ('image_thumb', models.ImageField(blank=True, default='project_thumbnail_imageDefault', upload_to='project/images/thumbnail')),
                ('image_lazy', models.ImageField(blank=True, default='project_lazy_imageDefault', upload_to='project/images/lazy/')),
                ('logo', models.ImageField(blank=True, default='project_logo_imageDefault', upload_to='project/images/logo')),
                ('description', models.TextField()),
                ('press_text', models.TextField(blank=True)),
                ('programm', models.TextField(blank=True)),
                ('poster_img', models.ImageField(blank=True, default='project_poster_imageDefault', upload_to='project/images/poster')),
                ('poster_img_thumb', models.ImageField(blank=True, default='project_poster_thumbnail_imageDefault', upload_to='project/images/poster/thumbnail')),
                ('youtube_id_one', models.CharField(blank=True, max_length=24, verbose_name='Youtube Video ID 1')),
                ('youtube_id_two', models.CharField(blank=True, max_length=24, verbose_name='Youtube Video ID 2')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teaching.Teacher')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
