# Generated by Django 3.0.3 on 2020-02-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
