# Generated by Django 4.1.1 on 2025-04-28 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kursname')),
                ('age_group', models.CharField(max_length=50, verbose_name='Altersgruppe')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurse',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Kontakt E-Mail')),
            ],
            options={
                'verbose_name': 'Lehrkraft',
                'verbose_name_plural': 'Lehrkräfte',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Montag', 'Montag'), ('Dienstag', 'Dienstag'), ('Mittwoch', 'Mittwoch'), ('Donnerstag', 'Donnerstag'), ('Freitag', 'Freitag'), ('Samstag', 'Samstag'), ('Sonntag', 'Sonntag')], max_length=10, verbose_name='Tag')),
                ('start_time', models.TimeField(verbose_name='Startzeit')),
                ('end_time', models.TimeField(verbose_name='Endzeit')),
                ('studio', models.CharField(blank=True, help_text='Optional, z.B. Studio 1', max_length=50, null=True, verbose_name='Studio')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='dance.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Zeitfenster',
                'verbose_name_plural': 'Zeitfenster',
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='dance.teacher', verbose_name='Lehrkraft'),
        ),
    ]
