# Generated by Django 4.1.1 on 2025-04-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0005_assign_locations'),
        ('dance', '9000_ensure_location_column'),
    ]

    operations = [
    ]
