# Generated by Django 2.2.5 on 2019-10-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='images',
            field=models.ImageField(blank=True, default='gallery_imageDefault', upload_to='gallery/images/'),
        ),
    ]
