# Generated by Django 2.2.5 on 2019-11-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['category', 'ordering'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
    ]
