# Generated by Django 2.2.5 on 2019-12-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20191113_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['category', '-ordering'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
    ]
