# Generated by Django 2.2.8 on 2019-12-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20191207_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_lazy',
            field=models.ImageField(blank=True, default='gallery_lazy_imageDefault', upload_to='gallery/images/lazy/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_thumbnail',
            field=models.ImageField(blank=True, default='gallery_thumbnail_imageDefault', upload_to='gallery/images/thumbnail'),
        ),
    ]
