# Generated by Django 2.2.8 on 2019-12-14 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20191212_0520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='images',
            new_name='image',
        ),
    ]
