# Generated by Django 3.0.2 on 2020-02-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20191216_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='copyright_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Copyright Owner of Photo'),
        ),
    ]
