# Generated by Django 3.0.7 on 2020-07-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_photo_copyright_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocategory',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
