# Generated by Django 3.0.7 on 2020-07-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_photocategory_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocategory',
            options={'ordering': ['ordering'], 'verbose_name': 'Photo Category', 'verbose_name_plural': 'Photo Categories'},
        ),
    ]
