# Generated by Django 2.2.5 on 2019-12-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='material name')),
                ('thumbnail', models.ImageField(blank=True, default='downloadsection_imageDefault', upload_to='downloadsection/images/')),
                ('file', models.FileField(blank=True, upload_to='downloadsection/files')),
                ('description', models.TextField(blank=True, null=True)),
                ('ordering', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
                'ordering': ['-ordering', 'name'],
            },
        ),
    ]
