# Generated by Django 2.2.5 on 2019-12-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloadsection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forms',
            options={'ordering': ['ordering', 'name'], 'verbose_name': 'Form', 'verbose_name_plural': 'Forms'},
        ),
    ]
