# Generated by Django 2.2.5 on 2019-10-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50, verbose_name='name of school')),
                ('school_logo', models.ImageField(blank=True, default='school_logo_imageDefault', upload_to='school/images/logo/')),
                ('contact_email', models.EmailField(blank=True, max_length=70, verbose_name='e-mail for contact')),
                ('adress_line', models.CharField(blank=True, max_length=80, verbose_name='street')),
                ('house_number', models.CharField(blank=True, max_length=80, verbose_name='house number')),
                ('postal_code', models.CharField(blank=True, max_length=30, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Country')),
            ],
            options={
                'verbose_name': 'Music School',
                'verbose_name_plural': 'Music Schools',
                'ordering': ('school_name',),
            },
        ),
    ]
