# Python CircleCI 2.0 configuration file
# Optimized for AlmaLinux 9 deployment compatibility
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Use Python 3.9 to match AlmaLinux 9 default Python version
      - image: cimg/python:3.9
      - image: cimg/postgres:13.8
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: mks
          POSTGRES_PASSWORD: test

    working_directory: ~/repo

    steps:
      - checkout
      
      # Install system dependencies that might be needed for AlmaLinux 9 compatibility
      - run:
          name: Install system dependencies
          command: |
            # Use faster mirror and add retry logic
            echo "Configuring apt to use mirror.ubuntu.com..."
            sudo sed -i 's/archive.ubuntu.com/mirror.ubuntu.com/g' /etc/apt/sources.list
            sudo sed -i 's/security.ubuntu.com/mirror.ubuntu.com/g' /etc/apt/sources.list
            
            # Add retry logic for apt-get update with exponential backoff
            n=0
            until [ "$n" -ge 5 ]
            do
              echo "Attempting apt-get update (attempt $((n+1))/5)..."
              sudo apt-get update -o Acquire::http::Timeout="10" -o Acquire::https::Timeout="10" -o Acquire::ftp::Timeout="10" && break
              n=$((n+1))
              if [ "$n" -lt 5 ]; then
                wait_time=$((15 * n))
                echo "apt-get update failed, waiting ${wait_time} seconds before retry..."
                sleep $wait_time
              fi
            done
            
            if [ "$n" -ge 5 ]; then
              echo "Failed to update package lists after 5 attempts, trying with --allow-releaseinfo-change"
              sudo apt-get update --allow-releaseinfo-change -o Acquire::http::Timeout="10" || true
            fi
            
            # Install packages with retry and timeout
            n=0
            until [ "$n" -ge 3 ]
            do
              echo "Installing packages (attempt $((n+1))/3)..."
              sudo apt-get install -y -o Acquire::http::Timeout="10" \
                build-essential \
                libpq-dev \
                python3-dev \
                libjpeg-dev \
                libpng-dev \
                libfreetype6-dev \
                libxml2-dev \
                libxslt1-dev \
                zlib1g-dev && break
              n=$((n+1))
              if [ "$n" -lt 3 ]; then
                echo "Package installation failed, retrying in 10 seconds..."
                sleep 10
              fi
            done
            
            if [ "$n" -ge 3 ]; then
              echo "WARNING: Some packages may not have been installed successfully"
              # Continue anyway as some packages might be optional
            fi

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            # Install requirements with verbose output for debugging
            pip install -r requirements.txt --verbose
            # Verify critical packages are installed
            echo "Verifying package installations..."
            python -c "import django; print(f'Django: {django.get_version()}')"
            python -c "import pandas; print(f'Pandas: {pandas.__version__}')"
            python -c "import numpy; print(f'Numpy: {numpy.__version__}')"

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}

      # Setup Django environment for testing
      - run:
          name: Setup Django environment
          command: |
            . venv/bin/activate
            # Create logs directory
            mkdir -p logs
            # Create a basic local_settings.py for testing if it doesn't exist
            if [ ! -f local_settings.py ]; then
              cat > local_settings.py << EOF
            # Test settings for CircleCI
            DEBUG = True
            
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': 'mks',
                    'USER': 'postgres',
                    'PASSWORD': 'test',
                    'HOST': 'localhost',
                    'PORT': '5432',
                }
            }
            
            SECRET_KEY = 'test-secret-key-for-ci-only'
            ALLOWED_HOSTS = ['*']
            EOF
            fi

      # run database migrations
      - run:
          name: run migrations
          command: |
            . venv/bin/activate
            export DJANGO_SETTINGS_MODULE=mks.settings
            python manage.py migrate --noinput

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            export DJANGO_SETTINGS_MODULE=mks.settings
            # Run Django system check first
            python manage.py check
            # Run the actual tests
            python manage.py test --keepdb --verbosity=2

      - store_artifacts:
          path: test-reports
          destination: test-reports
