# Generated by Django 2.2.5 on 2019-10-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, default='instruments_imageDefault', upload_to='instruments/images')),
                ('content', models.TextField()),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_description', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'ordering': ('instrument_name',),
            },
        ),
    ]
