# Generated by Django 5.2.1 on 2025-05-24 11:09

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_auto_20191201_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
