# Generated by Django 3.0.2 on 2020-01-31 11:55

from django.db import migrations, models
import todo.priority


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200130_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='finisheditems',
            name='priority',
            field=todo.priority.PriorityChoicesField(blank=True, choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4')], null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='finisheditems',
            name='created',
            field=models.DateField(default='2020-01-31'),
        ),
        migrations.AlterField(
            model_name='finisheditems',
            name='done_date',
            field=models.DateField(default='2020-01-31'),
        ),
        migrations.AlterField(
            model_name='finisheditems',
            name='due_date',
            field=models.DateField(blank=True, default='2020-01-31', null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2020-01-31'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(blank=True, default='2020-01-31', null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=todo.priority.PriorityChoicesField(blank=True, choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4')], null=True, verbose_name='Priority'),
        ),
    ]
