# Generated by Django 3.0.7 on 2021-06-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_auto_20210611_0700'),
        ('todo', '0026_auto_20210615_0842'),
    ]

    operations = [
    ]
