# Generated by Django 2.2.5 on 2019-09-27 04:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, default='author_imageDefault', upload_to='blog/author/images')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('number_of_posts', models.IntegerField()),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='blog/posts/images/')),
                ('date', models.DateField(blank=True, verbose_name='Blog Post Date')),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_description', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ('category', 'number_of_posts'),
            },
        ),
    ]
