# Generated by Django 3.0.2 on 2020-02-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200205_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='number_of_posts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
