# Generated by Django 3.0.2 on 2020-02-06 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200205_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Blog Post Date'),
        ),
    ]
