# Generated by Django 3.0.2 on 2020-02-06 09:01

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200206_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='published_year',
            field=models.IntegerField(default=blog.models.current_year, verbose_name='Year of Article'),
        ),
    ]
