# Generated by Django 5.2.1 on 2025-05-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blogpost_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_focus_x',
            field=models.FloatField(default=0.5, help_text='Horizontal focus point (0-1, left to right)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_focus_y',
            field=models.FloatField(default=0.5, help_text='Vertical focus point (0-1, top to bottom)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
