# Generated by Django 5.2 on 2025-05-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_newsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indextext',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content of Index page'),
        ),
    ]
