# Generated by Django 5.2.1 on 2025-05-24 11:09

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_indextext_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indextext',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content of Index page'),
        ),
    ]
