# Generated by Django 2.2.5 on 2019-09-26 14:49

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_form', models.CharField(choices=[('Einzelunterricht', 'Einzelunterricht'), ('Gruppenunterricht', 'Gruppenunterricht')], max_length=20, verbose_name='Unterrichtsmodell')),
                ('billing_form', models.CharField(choices=[('10', '10er Block'), ('5', '5er Block'), ('Semestrierung', 'Monatlicher Betrag')], max_length=20, verbose_name='Verrechnungsmodel')),
                ('minutes', models.IntegerField(choices=[(25, '25 Minuten'), (50, '50 Minuten')], verbose_name='Minutenanzahl')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preis')),
            ],
            options={
                'verbose_name': 'Lessonform',
                'verbose_name_plural': 'Lessonforms',
                'ordering': ('subject',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('image', models.ImageField(blank=True, default='teacher_imageDefault', upload_to='teachers/images/')),
                ('email', models.EmailField(max_length=254)),
                ('homepage', models.URLField(blank=True, max_length=80, verbose_name='Deine Website')),
                ('phone', phone_field.models.PhoneField(blank=True, default='+43 ', help_text='Telefonnummer', max_length=31, verbose_name='Telefonnummer')),
                ('socialSecurityField', models.CharField(blank=True, max_length=11, verbose_name='Sozialversicherungs Nummer')),
                ('iban', models.CharField(blank=True, max_length=24, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=20, verbose_name='BIC')),
                ('adress_line', models.CharField(max_length=80, verbose_name='Straße')),
                ('house_number', models.CharField(max_length=80, verbose_name='Hausnummer')),
                ('postal_code', models.CharField(max_length=4, verbose_name='Postleitzahl')),
                ('city', models.CharField(max_length=30, verbose_name='Wohnort')),
                ('bio', models.TextField(blank=True, null=True)),
                ('youtube_id_one', models.CharField(blank=True, max_length=24, verbose_name='Youtube Video ID 1')),
                ('youtube_id_two', models.CharField(blank=True, max_length=24, verbose_name='Youtube Video ID 2')),
                ('academic_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.AcademicTitle')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Country')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Gender')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teaching.Subject')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacher',
                'ordering': ('last_name',),
            },
        ),
    ]
