# Generated by Django 2.2.5 on 2019-10-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_auto_20191005_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='adress_line',
            field=models.CharField(blank=True, max_length=80, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='Wohnort'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='house_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='Hausnummer'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='postal_code',
            field=models.CharField(blank=True, max_length=4, verbose_name='Postleitzahl'),
        ),
    ]
