# Generated by Django 2.2.5 on 2019-11-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_auto_20191021_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('subject',), 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
