# Generated by Django 2.2.5 on 2019-10-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_auto_20191006_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcategory',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
