# Generated by Django 2.2.5 on 2019-11-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_auto_20191113_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectcategory',
            options={'ordering': ('name',)},
        ),
    ]
