# Generated by Django 2.2.5 on 2019-10-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_auto_20191007_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
