# Generated by Django 2.2.5 on 2019-11-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_auto_20191113_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(blank=True, to='teaching.Subject'),
        ),
    ]
