# Generated by Django 2.2.8 on 2019-12-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0005_auto_20191129_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='lazy_image',
            field=models.ImageField(blank=True, default='teachers/teacher_image_default.svg', upload_to='teachers/images/lazy/'),
        ),
    ]
