# Generated by Django 2.2.5 on 2019-10-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0005_auto_20191007_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='teachers/teacher_imageDefault', upload_to='teachers/images/'),
        ),
    ]
