# Generated by Django 2.2.8 on 2019-12-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0006_teacher_lazy_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('ordering', 'subject'), 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='subject',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
