# Generated by Django 2.2.8 on 2019-12-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0007_auto_20191213_0441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('ordering',), 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
