# Generated by Django 3.0.3 on 2020-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0008_auto_20191213_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='teachers/images/')),
            ],
            options={
                'verbose_name': 'Group Photo',
                'verbose_name_plural': 'Group Photos',
                'ordering': ('image',),
            },
        ),
    ]
