# Generated by Django 2.2.5 on 2019-10-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0008_auto_20191007_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='teachers/teacher_image_default.svg', upload_to='teachers/images/'),
        ),
    ]
