# Generated by Django 3.2.12 on 2022-04-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0010_groupphoto_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='complementary_subject',
            field=models.BooleanField(default=False),
        ),
    ]
