# Generated by Django 3.2.12 on 2022-04-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0011_subject_complementary_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='hidden_subject',
            field=models.BooleanField(default=False),
        ),
    ]
