# Generated by Django 4.0.4 on 2022-05-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0013_alter_subject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject_coordinator',
            field=models.ManyToManyField(blank=True, to='teaching.subjectcategory'),
        ),
    ]
