# Generated by Django 4.0.4 on 2022-05-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0014_teacher_subject_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcategory',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
