# Generated by Django 4.1.1 on 2024-11-16 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0015_subjectcategory_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bic',
            field=models.CharField(help_text='Bank Identifier Code (BIC) for Austria', max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid BIC format for Austria. Must be 8 or 11 characters.', regex='^[A-Z]{4}AT[A-Z0-9]{2}([A-Z0-9]{3})?$')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='iban',
            field=models.CharField(help_text='International Bank Account Number (IBAN) for Austria', max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid IBAN format for Austria. Must be 20 characters.', regex='^AT[0-9]{2}[0-9]{16}$')]),
        ),
    ]
