# Generated by Django 3.2.13 on 2024-11-26 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0016_alter_teacher_bic_alter_teacher_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bic',
            field=models.CharField(blank=True, help_text='Bank Identifier Code (BIC) for Austria', max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid BIC format for Austria. Must be 8 or 11 characters.', regex='^[A-Z]{4}AT[A-Z0-9]{2}([A-Z0-9]{3})?$')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='iban',
            field=models.CharField(blank=True, help_text='International Bank Account Number (IBAN) for Austria', max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid IBAN format for Austria. Must be 20 characters.', regex='^AT[0-9]{2}[0-9]{16}$')]),
        ),
    ]
