# Generated by Django 5.2.1 on 2025-05-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0017_auto_20241126_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject_coordinator_active',
            field=models.BooleanField(default=True, help_text='Bestimmt ob die Fachgruppenleitung aktiv ist', verbose_name='Fachgruppenleitung aktiv'),
        ),
    ]
