# Generated by Django 5.2.1 on 2025-05-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0018_teacher_subject_coordinator_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='socialSecurityField',
        ),
    ]
