# Generated by Django 4.2.21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Aktiviert den Wartungsmodus für normale Benutzer')),
                ('title', models.CharField(default='Wartungsarbeiten', help_text='Titel der Wartungsseite', max_length=200)),
                ('message', models.TextField(default='Wir führen gerade ein Update durch und sind bald wieder für Sie da!', help_text='Nachricht die auf der Wartungsseite angezeigt wird')),
                ('expected_downtime', models.CharField(blank=True, help_text="Erwartete Dauer der Wartung (z.B. '2 Stunden')", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wartungsmodus',
                'verbose_name_plural': 'Wartungsmodus',
            },
        ),
    ]