# Generated by Django 4.1.1 on 2024-11-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='event_name',
            field=models.CharField(default='Die Hexe Rabaukel bekommt Weihnachtspost', max_length=255),
        ),
        migrations.AddField(
            model_name='invitation',
            name='location',
            field=models.TextField(default='Grillparzercampus Orchestersaal, Grillparzerstraße 17, 3100 St. Pölten'),
        ),
    ]
