# Generated by Django 4.1.1 on 2024-11-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_invitation_event_date_invitation_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='number_of_guests',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Anzahl der Begleitpersonen'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='location',
            field=models.TextField(blank=True, default='Grillparzercampus Orchestersaal, Grillparzerstraße 17, 3100 St. Pölten', null=True),
        ),
    ]
