# Generated by Django 4.2.21 on 2025-05-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_invitation_event_alter_invitation_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='event_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
